// Generated by CoffeeScript 1.6.3
var MainCtrl, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

MainCtrl = (function(_super) {
  __extends(MainCtrl, _super);

  function MainCtrl() {
    _ref = MainCtrl.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  MainCtrl.prototype.initialize = function() {
    var CONFIG;
    CONFIG = {
      name: 'universitapp',
      version: '1.0',
      size: 65536,
      schema: [
        {
          name: 'asignatures',
          drop: false,
          fields: {
            id: 'INTEGER PRIMARY KEY AUTOINCREMENT',
            name: 'STRING',
            semester: 'INTEGER',
            room: 'TEXT'
          }
        }, {
          name: 'breaks',
          drop: false,
          fields: {
            id: 'INTEGER PRIMARY KEY AUTOINCREMENT',
            "break": 'INTEGER',
            asignature_id: 'INTEGER',
            date: 'STRING'
          }
        }, {
          name: 'scores',
          drop: false,
          fields: {
            id: 'INTEGER PRIMARY KEY AUTOINCREMENT',
            score: 'INTEGER',
            type: 'STRING',
            "break": 'INTEGER',
            asignature_id: 'INTEGER',
            date: 'STRING'
          }
        }
      ]
    };
    Lungo.Data.Sql.init(CONFIG);
    return __Controller.Asignature.initialize();
  };

  MainCtrl.prototype.elements = {
    "#txtMateria": "asignatura",
    "#txtSemestre": "semestre"
  };

  return MainCtrl;

})(Monocle.Controller);

Lungo.ready(function() {
  var configBreak;
  configBreak = Lungo.Data.Storage.persistent("configBreaks");
  if (configBreak) {
    $$('#liBreakConfig').remove();
  }
  __Controller.Main = new MainCtrl("section#main");
  return __Controller.Main.initialize();
});
