// Generated by CoffeeScript 1.6.3
var _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

__Model.Breaks = (function(_super) {
  __extends(Breaks, _super);

  function Breaks() {
    _ref = Breaks.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  Breaks.fields("break");

  Breaks.prototype.validate = function() {
    if (!this["break"]) {
      return "El corte es requerido";
    }
  };

  return Breaks;

})(Monocle.Model);
