// Generated by CoffeeScript 1.6.3
var _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

__View.Asignature = (function(_super) {
  __extends(Asignature, _super);

  function Asignature() {
    _ref = Asignature.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  Asignature.prototype.container = "section#main article#art_main ul#ulAsignatures";

  Asignature.prototype.template = "{{#data}}\n	<li>\n		            <div class=\"right\" id=\"{{id}}\">\n		            	<a href=\"#\">\n		            		<span class=\"icon trash red\"></span>\n		            	</a>\n		            </div>\n		            <a data-action=\"aAsig\" id=\"{{id}}\">\n			<div class=\"left\">\n            	<p>Salon {{room}}</p>\n            </div>\n            <br/>\n			<small>{{semester}} semestre</small>\n			<strong>{{name}}</strong>\n		</a>\n	</li>\n{{/data}}";

  Asignature.prototype.events = {
    "tap article#art_main ul li [data-action=aAsig]": "onTap",
    "tap article#art_main ul li div.right": "onDelete"
  };

  Asignature.prototype.onTap = function(e) {
    var id;
    id = e.currentTarget.id;
    return __Controller.Break.getBreaks(id)();
  };

  Asignature.prototype.onDelete = function(e) {
    var id;
    id = e.currentTarget.id;
    return __Controller.Asignature.deleteAsig(id)();
  };

  return Asignature;

})(Monocle.View);
