// Generated by CoffeeScript 1.6.3
var _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

__View.Breaks = (function(_super) {
  __extends(Breaks, _super);

  function Breaks() {
    _ref = Breaks.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  Breaks.prototype.container = "section#sect_breaks article#art_breaks ul";

  Breaks.prototype.template = "{{#data}}\n	<li class=\"liId\" id=\"{{break}}\">\n		<input type=\"hidden\" value=\"{{asignature_id}}\" />\n		<strong>Corte # {{break}}</strong>\n	</li>\n{{/data}}";

  Breaks.prototype.events = {
    "tap article#art_breaks ul li.liId": "onTap"
  };

  Breaks.prototype.onTap = function(e) {
    var id;
    id = e.currentTarget.id;
    return __Controller.Break.getViewScore(id)();
  };

  return Breaks;

})(Monocle.View);
